!This collection of subroutines conducts different necessary
! calculation like: 1D, 2D integration, FFT etc.
!
!
!=============================================================
!1D INTEGRATION SUBROUTINE
!X1D(INPUT): X-ARRAY IN 1D
!F(INPUT, REAL): FUNCTIONAL ARRAY IN 1D
!2 TYPES OF CHARACTERS FOR INTEGRATION: 'SP'-SPLINE RULE
!                                      'TR'-TRAPEZOIDAL RULE
!XINTEGRATE_VAL(OUTPUT): A REAL NUMBER
!Need: libs/INTEGRATE.f SUBROUTINE
!=============================================================

SUBROUTINE XINTGR1D (X1D, F, CHARAC, NCOUNT, XINTGR_VAL)
IMPLICIT REAL*8(A-H,O-Z)
CHARACTER(LEN=2) CHARAC
REAL*8, INTENT(IN) :: X1D, F
REAL*8, INTENT(OUT) :: XINTGR_VAL
DIMENSION X1D(NCOUNT)
DIMENSION F(NCOUNT)

DIMENSION C(3,NCOUNT)

A1= MINVAL(X1D)
B1= MAXVAL(X1D)

K=2
CALL SPLINE(X1D,F,NCOUNT,C,IER)
CALL SPLINT(A1,B1,SINT,TINT,NCOUNT,X1D,F,C,IER)

IF (CHARAC .EQ. 'TR') THEN
   XINTGR_VAL = TINT
ELSE IF (CHARAC .EQ. 'SP') THEN
   XINTGR_VAL = SINT
ENDIF

END SUBROUTINE XINTGR1D


!=============================================================
!2D INTEGRATION FUNCTION
!X1D(INPUT): X-ARRAY IN 1D
!Y1D(INPUT): Y-ARRAY IN 1D
!F(INPUT, REAL): FUNCTIONAL ARRAY IN 2D
!2 TYPE OF CHARACTERS FOR INTEGRATION: 'SP'-SPLINE RULE
!                                      'TR'-TRAPEZOIDAL RULE
!XINTEGRATE_VAL(OUTPUT): A REAL NUMBER
!=============================================================

FUNCTION XINTEGRATE2D (X1D, Y1D, F, CHARAC)
USE CONST
IMPLICIT REAL*8(A-H,O-Z)
CHARACTER(LEN=2) CHARAC
INTEGER, PARAMETER :: N= L * M
REAL*8, INTENT(IN) :: X1D, Y1D, F
DIMENSION X1D(L), Y1D(M), F(L, M)

DIMENSION C(3,M), Z(N)
DIMENSION XARR_INT(L), C2(3, L), XARR_INT2(L), XNEXT(L)

A1= MINVAL(X1D)
B1= MAXVAL(X1D)
A2= MINVAL(Y1D)
B2= MAXVAL(Y1D)


DO I=1, L, 1    

    K=4
    CALL SPLINE(Y1D,F(I, :),M,C,IER)
    CALL SPLINT(A2,B2,SINT,TINT,M,Y1D,F(I, :),C,IER)
    XARR_INT(I)=TINT
    XARR_INT2(I) = SINT
ENDDO 

IF (CHARAC .EQ. 'TR') THEN
   XNEXT = XARR_INT
ELSE IF (CHARAC .EQ. 'SP') THEN
   XNEXT = XARR_INT2
ENDIF

K=4
CALL SPLINE(X1D,XNEXT,L,C2,IER)
CALL SPLINT(A1,B1,SINT,TINT,L,X1D,XARR_INT,C2,IER)

IF (CHARAC .EQ. 'TR') THEN
   XINTEGRATE_VAL = TINT
ELSE IF (CHARAC .EQ. 'SP') THEN
   XINTEGRATE_VAL = SINT
ENDIF

XINTEGRATE2D =  XINTEGRATE_VAL
END


!=============================================================
!COMPLEX VALUE FFT IN 2D.
!C(INPUT, COMPLEX): 2D INPUT ARRAY
!X(CHARACTER, INPUT): 'F': FORWARD FOURIER TRANSFORM
!                     'B': BACKWARD FOURIER TRANSFORM
!CFFT(OUTPUT): A 2D ARRAY
!NEED SUBROUTINE(S): 'libs/fftpack5.1.f'
!=============================================================
SUBROUTINE FFT2D(C, CHARAC, CFFT)
USE CONST
IMPLICIT REAL*8(A-H,O-Z)

CHARACTER(LEN=1), INTENT(IN) :: CHARAC
COMPLEX , INTENT(IN):: C
COMPLEX, INTENT(OUT):: CFFT

COMPLEX, ALLOCATABLE :: CSTORE(:, :)
REAL(8), ALLOCATABLE :: WORK(:)
REAL(8), ALLOCATABLE :: WSAVE(:)

PARAMETER ( LENWRK = 2 * L * M )
PARAMETER ( LENSAV = 2 * L + INT ( LOG ( REAL ( L ) ) /LOG ( 2.0E+00 ) )  &
   + 2 * M +INT ( LOG ( REAL ( M ) ) / LOG ( 2.0E+00 ) ) + 8 )

DIMENSION C(L,M)
DIMENSION CFFT(L,M)
 
ALLOCATE (CSTORE(L, M))
ALLOCATE (WORK(LENWRK))
ALLOCATE (WSAVE(LENSAV))

CSTORE = C
CALL CFFT2I ( L, M, WSAVE, LENSAV, IER )
LDIM = L

IF (CHARAC .EQ. 'F') THEN
CALL CFFT2F ( LDIM, L, M, CSTORE, WSAVE, LENSAV, WORK, LENWRK, IER )
ELSE IF (CHARAC .EQ. 'B') THEN
CALL CFFT2B ( LDIM, L, M, CSTORE, WSAVE, LENSAV, WORK, LENWRK , IER )
ENDIF

CFFT = CSTORE
DEALLOCATE (CSTORE)
DEALLOCATE (WORK)
DEALLOCATE (WSAVE)

END SUBROUTINE FFT2D

